### ISSUE TITLE
HF Space

### ISSUE THREAD

**Issue by Samoed** [avidale/encodechka#10]
Решил сделать отдельное issue для обсуждения leaderboard (из #9). 

Я посмотрел как делает MTEB и [они собирают evaluation metrics](https://huggingface.co/spaces/mteb/leaderboard/blob/main/app.py#L240), которые хранятся в readme.md у каждой модели отдельно (например [Alibaba-NLP/gte-Qwen2-7B-instruct](https://huggingface.co/Alibaba-NLP/gte-Qwen2-7B-instruct/blob/main/README.md)), поэтому не думаю что получится подтягивать информацию о метриках. Пока можно просто какую-то мета-информамцию только получать о моделях.

[Документация по evaluation metrics](https://huggingface.co/docs/hub/model-cards#evaluation-results). Как запускать [MTEB](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_model.md). Как метрики создаются в [MTEB](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/cli.py#L251). Можно сделать по аналогии (генерировать yaml для каждой метрики), чтобы можно было сразу на карточку модели добавить.

**Comment by Samoed** [comment]
@avidale  Если тебе это интересно, то могу попробовать добавить такую генерацию метрик

**Comment by avidale** [comment]
Мне это не супер интересно, потому что в целом я скорее подумываю вообще закопать бенчмарк Encodechka как самостоятельную сущность, встроив его напрямую в MTEB.

**Comment by Samoed** [comment]
Да, там на mteb есть конфиг для теста русского языка, но его использования кем-то я не нашел

**Comment by Samoed** [comment]
Сейчас как раз активно начинают развивать русский язык там из Салюта https://github.com/embeddings-benchmark/mteb/pull/815 https://github.com/embeddings-benchmark/mteb/pull/962

**Comment by avidale** [comment]
В принципе, ruMTEB выехал (https://habr.com/ru/companies/sberdevices/articles/831150/), и Энкодечку можно с читсой совестью закапывать :)

**Comment by Samoed** [comment]
Скоро еще лидиерборд сделаю для русского, чтобы пользоваться можно было

**Comment by Samoed** [comment]
https://github.com/embeddings-benchmark/leaderboard/pull/21

**Comment by Samoed** [comment]
Теперь добавили https://huggingface.co/spaces/mteb/leaderboard

**Comment by Samoed** [comment]
Теперь добавили https://huggingface.co/spaces/mteb/leaderboard
