### ISSUE TITLE
[ Feature ] Перенос данных в Google Таблицы

### ISSUE THREAD

**Issue by potat-dev** [avidale/encodechka#3]
Для более удобной сортировки / визуализации данных, было бы полезно перенести данные в Google Таблицы, и в дальнейшем обновлять данные только там, вместо таблиц в README. Предлагаю использовать данный шаблон: https://docs.google.com/spreadsheets/d/1prUJ_zI5kJPUgcaEpEcz2A8VY5yfX-KlnbPFLxLi7KM/edit

**Comment by avidale** [comment]
Спасибо за идею!
Я подумываю вообще встроить этот бенчмарк в MTEB, для большей visibility. 
Ну из лидерборда MTEB можно будет копировать скоры хоть в Google Sheets, хоть в другие места.
